version: 2.1
orbs:
  node: circleci/node@4.1.0

variables:
  - &workspace /home/circleci/project
  - &build_image circleci/node:14.1.0-browsers

jobs:
  checkout_code:
    docker:
      - image: *build_image
    working_directory: *workspace
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          app-dir: .
      - persist_to_workspace:
          root: *workspace
          paths:
            - .
  test_lint:
    docker:
      - image: *build_image
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run: npm run lint
  build:
    docker:
      - image: *build_image
    working_directory: *workspace
    parameters:
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Build App
          command: npm run build

  e2e:
    docker:
      - image: cimg/node:14.14-browsers
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Running landing page e2e test
          command: npm run e2e
      - store_artifacts:
          path: /home/circleci/project/.screenshots

workflows:
  version: 2

  feature_branch:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore:
                - main
      - test_lint:
          requires:
            - checkout_code
      - build:
          name: build_feature
          requires:
            - checkout_code

  main:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - main
      - e2e:
          context: test-envs
          requires:
            - checkout_code
