export { default as DiversityAndInclusionSection } from './diversity-and-inclusion-section'
export { default as ExecutiveTeamSection } from './executive-team-section'
export { default as HowItWorks } from './how-it-works-section'
export { default as LogoSection } from './logo-section'
export { default as OpensourceSection } from './opensource-section'
export { default as WhatsRight } from './do-whats-right-section'
export { default as TimelineSection } from './timeline-section'
export { default as WhyCommitSection } from './why-commit-section'
